name: Update database daily

on:
  schedule:
    - cron: '0 23 * * *' # Runs daily at 6 pm EST (11pm UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  run-daily-function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # or whatever version you use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure this file exists

      - name: Run update_db()
        run: |
          python flu_finder_src/utils/db_methods.py